---

- name: copy keepalive.conf file to node
  template:
     src: keepalived.conf.j2
     dest: /etc/keepalived/keepalived.conf
     mode: 0644
  notify: Restart keepalived

- name: copy haproxy check scripts
  template:
     src:  check_haproxy.sh.j2
     dest: /etc/keepalived/check_haproxy.sh
     mode: 0755
- name: start keepalived service
  service: name=keepalived enabled=yes state=started


