---
- hosts: testserver
  remote_user: admin
  become: yes
  vars:
    - ngx_proxy_cache_path: /data/app/nginx/cache levels=1:2 keys_zone=mycache:10m inactive=24h max_size=5g
    - config: www.c.com.conf
    - ngx_upstreams:
      - name: upstreamtest
        strategy: ip_hash
        servers:
          - 192.168.10.163:8080 weight=3 max_fails=2 fail_timeout=2
          - 192.168.10.164:8080  weight=2 max_fails=2 fail_timeout=2
          #- 192.168.10.165 backup
    - ngx_vhosts:
        - listen: 80
          server_name: www.c.com
          access_log: /data/log/nginx/www.c.com_access.log main
          error_log: /data/log/nginx/www.c.com_error.log
          extra_parameters: |
            location / {
                 proxy_pass   http://upstreamtest;
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_connect_timeout 30;
                 proxy_send_timeout 60;
                 proxy_read_timeout 60;
                 proxy_buffer_size 32k;
                 proxy_buffering on;
                 proxy_buffers 4 128k;
                 proxy_busy_buffers_size 256k;
                 proxy_max_temp_file_size 256k;
                 proxy_cache mycache;
                 proxy_cache_valid 200 302 1d;
                 proxy_cache_valid any 1m;
                 proxy_cache_key $host$uri$is_args$args;
                 proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
                }

  roles:
    - { role: nginx }
